sample_count: 1000
device: gpu
engine: onnxruntime
checkpoint_dir: ./data
repeat_times: 100
submodule_level: 2
specified_sample_space:
  - 
    - layer\d.\d.conv1: {start: 0.1,  end: 1.0, step: 0.1}
    - layer\d.\d.conv2|layer\d.0.downsample.0: {start: 0.1,  end: 1.0, step: 0.1}
